
package fiap.scj.ws.soap.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MinhaSaudeImplService", targetNamespace = "http://soap.ws.scj.fiap/", wsdlLocation = "http://localhost:8080/minhasaude?wsdl")
public class MinhaSaudeImplService
    extends Service
{

    private final static URL MINHASAUDEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException MINHASAUDEIMPLSERVICE_EXCEPTION;
    private final static QName MINHASAUDEIMPLSERVICE_QNAME = new QName("http://soap.ws.scj.fiap/", "MinhaSaudeImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/minhasaude?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MINHASAUDEIMPLSERVICE_WSDL_LOCATION = url;
        MINHASAUDEIMPLSERVICE_EXCEPTION = e;
    }

    public MinhaSaudeImplService() {
        super(__getWsdlLocation(), MINHASAUDEIMPLSERVICE_QNAME);
    }

    public MinhaSaudeImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MINHASAUDEIMPLSERVICE_QNAME, features);
    }

    public MinhaSaudeImplService(URL wsdlLocation) {
        super(wsdlLocation, MINHASAUDEIMPLSERVICE_QNAME);
    }

    public MinhaSaudeImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MINHASAUDEIMPLSERVICE_QNAME, features);
    }

    public MinhaSaudeImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MinhaSaudeImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MinhaSaudeImpl
     */
    @WebEndpoint(name = "MinhaSaudeImplPort")
    public MinhaSaudeImpl getMinhaSaudeImplPort() {
        return super.getPort(new QName("http://soap.ws.scj.fiap/", "MinhaSaudeImplPort"), MinhaSaudeImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MinhaSaudeImpl
     */
    @WebEndpoint(name = "MinhaSaudeImplPort")
    public MinhaSaudeImpl getMinhaSaudeImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://soap.ws.scj.fiap/", "MinhaSaudeImplPort"), MinhaSaudeImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MINHASAUDEIMPLSERVICE_EXCEPTION!= null) {
            throw MINHASAUDEIMPLSERVICE_EXCEPTION;
        }
        return MINHASAUDEIMPLSERVICE_WSDL_LOCATION;
    }

}
